/**
 * Admin UI kit. Import from '@/admin-kit'.
 * Spec: docs/superpowers/specs/2026-09-03-admin-ui-kit-design.md
 */
export { AdminPage } from './AdminPage'
export type { AdminPageProps, AdminPageWidth } from './AdminPage'
export { AdminPageHeader } from './AdminPageHeader'
export type { AdminPageHeaderProps, Breadcrumb } from './AdminPageHeader'
export { AdminTabs, tabId, tabPanelId, tabPanelProps } from './AdminTabs'
export type { AdminTab, AdminTabsProps, AdminTabsAccent } from './AdminTabs'
export { AdminModal } from './AdminModal'
export type { AdminModalProps, AdminModalSize } from './AdminModal'
export { AdminTable, AdminPagination } from './AdminTable'
export type { AdminTableColumn, AdminTableProps, AdminPaginationProps, SortDirection } from './AdminTable'
export { Badge } from './Badge'
export type { BadgeProps, BadgeTone } from './Badge'
export { SectionCard } from './SectionCard'
export type { SectionCardProps } from './SectionCard'
export { StatCard } from './StatCard'
export type { StatCardProps } from './StatCard'
export { EmptyState, LoadingState, ErrorState } from './states'
export type { EmptyStateProps, LoadingStateProps, ErrorStateProps } from './states'
export { SearchInput } from './SearchInput'
export type { SearchInputProps } from './SearchInput'
export { Avatar } from './Avatar'
export type { AvatarProps, AvatarSize } from './Avatar'
export { useUrlParamState } from './hooks'
export * from './format'
export * as tokens from './tokens'
