/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    people: Person;
    teams: Team;
    'faceit-leagues': FaceitLeague;
    production: Production;
    'organization-staff': OrganizationStaff;
    matches: Match;
    'tournament-templates': TournamentTemplate;
    'faceit-seasons': FaceitSeason;
    'social-posts': SocialPost;
    'events-anchor': EventsAnchor;
    'graphics-anchor': GraphicsAnchor;
    'video-anchor': VideoAnchor;
    'recruitment-listings': RecruitmentListing;
    'recruitment-applications': RecruitmentApplication;
    tasks: Task;
    'discord-polls': DiscordPoll;
    'discord-category-templates': DiscordCategoryTemplate;
    'audit-logs': AuditLog;
    'error-logs': ErrorLog;
    'cron-job-runs': CronJobRun;
    'active-sessions': ActiveSession;
    users: User;
    'ignored-duplicates': IgnoredDuplicate;
    'invite-links': InviteLink;
    media: Media;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'faceit-leagues': FaceitLeaguesSelect<false> | FaceitLeaguesSelect<true>;
    production: ProductionSelect<false> | ProductionSelect<true>;
    'organization-staff': OrganizationStaffSelect<false> | OrganizationStaffSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    'tournament-templates': TournamentTemplatesSelect<false> | TournamentTemplatesSelect<true>;
    'faceit-seasons': FaceitSeasonsSelect<false> | FaceitSeasonsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'events-anchor': EventsAnchorSelect<false> | EventsAnchorSelect<true>;
    'graphics-anchor': GraphicsAnchorSelect<false> | GraphicsAnchorSelect<true>;
    'video-anchor': VideoAnchorSelect<false> | VideoAnchorSelect<true>;
    'recruitment-listings': RecruitmentListingsSelect<false> | RecruitmentListingsSelect<true>;
    'recruitment-applications': RecruitmentApplicationsSelect<false> | RecruitmentApplicationsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'discord-polls': DiscordPollsSelect<false> | DiscordPollsSelect<true>;
    'discord-category-templates': DiscordCategoryTemplatesSelect<false> | DiscordCategoryTemplatesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'error-logs': ErrorLogsSelect<false> | ErrorLogsSelect<true>;
    'cron-job-runs': CronJobRunsSelect<false> | CronJobRunsSelect<true>;
    'active-sessions': ActiveSessionsSelect<false> | ActiveSessionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'ignored-duplicates': IgnoredDuplicatesSelect<false> | IgnoredDuplicatesSelect<true>;
    'invite-links': InviteLinksSelect<false> | InviteLinksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'production-dashboard': ProductionDashboard;
    'social-media-settings': SocialMediaSetting;
    'social-media-config': SocialMediaConfig;
    'graphics-dashboard': GraphicsDashboard;
    'video-editing-dashboard': VideoEditingDashboard;
    'events-dashboard': EventsDashboard;
    'scouting-dashboard': ScoutingDashboard;
    'discord-server-manager': DiscordServerManager;
    'audit-log-viewer': AuditLogViewer;
    'cron-monitor': CronMonitor;
    'error-dashboard': ErrorDashboard;
    'active-sessions-viewer': ActiveSessionsViewer;
    'database-health': DatabaseHealth;
    'data-consistency': DataConsistency;
    'error-harvester-state': ErrorHarvesterState;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'production-dashboard': ProductionDashboardSelect<false> | ProductionDashboardSelect<true>;
    'social-media-settings': SocialMediaSettingsSelect<false> | SocialMediaSettingsSelect<true>;
    'social-media-config': SocialMediaConfigSelect<false> | SocialMediaConfigSelect<true>;
    'graphics-dashboard': GraphicsDashboardSelect<false> | GraphicsDashboardSelect<true>;
    'video-editing-dashboard': VideoEditingDashboardSelect<false> | VideoEditingDashboardSelect<true>;
    'events-dashboard': EventsDashboardSelect<false> | EventsDashboardSelect<true>;
    'scouting-dashboard': ScoutingDashboardSelect<false> | ScoutingDashboardSelect<true>;
    'discord-server-manager': DiscordServerManagerSelect<false> | DiscordServerManagerSelect<true>;
    'audit-log-viewer': AuditLogViewerSelect<false> | AuditLogViewerSelect<true>;
    'cron-monitor': CronMonitorSelect<false> | CronMonitorSelect<true>;
    'error-dashboard': ErrorDashboardSelect<false> | ErrorDashboardSelect<true>;
    'active-sessions-viewer': ActiveSessionsViewerSelect<false> | ActiveSessionsViewerSelect<true>;
    'database-health': DatabaseHealthSelect<false> | DatabaseHealthSelect<true>;
    'data-consistency': DataConsistencySelect<false> | DataConsistencySelect<true>;
    'error-harvester-state': ErrorHarvesterStateSelect<false> | ErrorHarvesterStateSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 📄 Create and edit website pages with rich content, blocks, and SEO settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🖼️ Upload and manage images, videos, and other media files used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * 👥 Centralized collection for all people (players, staff, casters, etc.). This is the single source of truth for person profiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * Full display name. This name will be used across all teams and staff positions. Tip: Use the exact name format you want displayed (e.g., "Malevolence" not "malevolence").
   */
  name: string;
  /**
   * Auto-generated from name. You can customize it if needed.
   */
  slug?: string | null;
  /**
   * Optional biography or description
   */
  bio?: string | null;
  /**
   * Profile photo (optional)
   */
  photo?: (number | null) | Media;
  /**
   * Social media links. These will be displayed on player pages. Tip: Use full URLs (e.g., https://twitter.com/username) for best results.
   */
  socialLinks?: {
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * Twitch channel URL
     */
    twitch?: string | null;
    /**
     * YouTube channel URL
     */
    youtube?: string | null;
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * TikTok profile URL
     */
    tiktok?: string | null;
    /**
     * Add any additional social media or personal links with custom labels
     */
    customLinks?:
      | {
          /**
           * Display name for this link (e.g., "Discord", "Website", "Linktree")
           */
          label: string;
          /**
           * Full URL for this link
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Internal notes about this person (not displayed publicly)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏆 Manage all Elemental teams, including rosters, staff, and achievements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * Team display name (e.g., "Garden", "Dragon", "Fire")
   */
  name: string;
  /**
   * Path to logo image (e.g., /logos/elmt_garden.png). Logo should be uploaded to /public/logos/
   */
  logo: string;
  /**
   * Geographic region where the team competes
   */
  region?: ('NA' | 'EMEA' | 'SA' | 'Other') | null;
  /**
   * Team skill rating or tier (e.g., "4.5K", "FACEIT Masters", "FACEIT Expert", "FACEIT Advanced", "3.5K")
   */
  rating?: string | null;
  /**
   * Custom theme color for the team page hero background. Pick a color that complements the logo. Leave empty to auto-detect based on team name.
   */
  themeColor?: string | null;
  /**
   * Optional team bio or description to display on the team page. Great for team history, philosophy, or fun facts!
   */
  bio?: string | null;
  /**
   * Whether this team is currently active and competing
   */
  active?: boolean | null;
  /**
   * Notable achievements and accomplishments for this team
   */
  achievements?:
    | {
        /**
         * Achievement text (e.g., "Faceit S5 Advanced Champions")
         */
        achievement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Team managers. Use the Person field to link to the People collection (recommended). Tip: A person can be both manager and coach - they will appear once with both roles on their player page. Click "Create Person" to add someone new without leaving this page.
   */
  manager?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Team coaches. Use the Person field to link to the People collection (recommended). Tip: A person can be both manager and coach - they will appear once with both roles on their player page. Click "Create Person" to add someone new without leaving this page.
   */
  coaches?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Team captains. Use the Person field to link to the People collection (recommended). Tip: A player can be both captain and on the roster - they will appear once with both roles. Click "Create Person" to add someone new without leaving this page.
   */
  captain?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Co-captain (link to People collection).
   */
  coCaptain?: (number | null) | Person;
  /**
   * Active roster players. Use the Person field to link to the People collection (recommended). Each player must have a role (Tank, DPS, or Support). Tip: Click "Create Person" to add someone new without leaving this page.
   */
  roster?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        /**
         * Player role in-game
         */
        role: 'tank' | 'dps' | 'support';
        id?: string | null;
      }[]
    | null;
  /**
   * Substitute players who can fill in when needed. Use the Person field to link to the People collection (recommended), or use Name field for backward compatibility.
   */
  subs?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * 🏆 Enable FaceIt competitive tracking for this team
   */
  faceitEnabled?: boolean | null;
  /**
   * FaceIt Team ID (e.g., bc03efbc-725a-42f2-8acb-c8ee9783c8ae) - Find this on the team's FaceIt profile URL
   */
  faceitTeamId?: string | null;
  /**
   * 🎯 Current league/season this team is competing in - Selecting this auto-creates the season entry
   */
  currentFaceitLeague?: (number | null) | FaceitLeague;
  /**
   * Display FaceIt competitive data on team page frontend
   */
  faceitShowCompetitiveSection?: boolean | null;
  /**
   * 📊 Current active season data (auto-populated)
   */
  currentFaceitSeason?: (number | null) | FaceitSeason;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug?: string | null;
  /**
   * Tournaments this team is currently participating in (auto-generates weekly matches)
   */
  activeTournaments?: (number | TournamentTemplate)[] | null;
  /**
   * Team skill rating (SR) for sorting team cards
   */
  competitiveRating?: number | null;
  /**
   * Discord message ID for team card (auto-managed)
   */
  discordCardMessageId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚙️ FaceIt league templates - Admin-only. Teams select from these when enabling FaceIt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faceit-leagues".
 */
export interface FaceitLeague {
  id: number;
  /**
   * Display name (e.g., "Season 7 Advanced NA")
   */
  name: string;
  /**
   * Is this the current active season?
   */
  isActive?: boolean | null;
  /**
   * Season number (e.g., 7)
   */
  seasonNumber: number;
  division: 'Masters' | 'Expert' | 'Advanced' | 'Open';
  region: 'NA' | 'EMEA' | 'SA';
  /**
   * Conference name (e.g., "Central") - optional
   */
  conference?: string | null;
  /**
   * FaceIt League ID (from standings URL)
   */
  leagueId: string;
  /**
   * FaceIt Season ID (from standings URL)
   */
  seasonId: string;
  /**
   * FaceIt Stage ID (from ?stage= parameter in standings URL)
   */
  stageId: string;
  /**
   * FaceIt Championship ID (optional - needed for match data sync. Try using League ID if unknown)
   */
  championshipId?: string | null;
  /**
   * Internal notes about this league/season
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏆 Team FaceIt seasons - Auto-managed through team pages (backend only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faceit-seasons".
 */
export interface FaceitSeason {
  id: number;
  /**
   * Which ELMT team this season data belongs to
   */
  team: number | Team;
  /**
   * ⭐ RECOMMENDED: Select a league template to auto-fill championship/stage/league IDs
   */
  faceitLeague?: (number | null) | FaceitLeague;
  /**
   * FaceIt Team ID for this specific team (e.g., bc03efbc-725a-42f2-8acb-c8ee9783c8ae)
   */
  faceitTeamId: string;
  /**
   * FaceIt Championship ID (auto-filled from league, or enter manually)
   */
  championshipId?: string | null;
  /**
   * FaceIt League ID (auto-filled from league, or enter manually)
   */
  leagueId?: string | null;
  /**
   * FaceIt Season ID (auto-filled from league, or enter manually)
   */
  seasonId?: string | null;
  /**
   * FaceIt Stage ID (auto-filled from league, or enter manually)
   */
  stageId?: string | null;
  /**
   * ✨ Auto-filled from league template on save (editable before save)
   */
  seasonName: string;
  /**
   * Is this the current active season?
   */
  isActive?: boolean | null;
  /**
   * ✨ Auto-filled from league template on save
   */
  division: 'Masters' | 'Expert' | 'Advanced' | 'Open';
  /**
   * ✨ Auto-filled from league template on save
   */
  region: 'NA' | 'EMEA' | 'SA';
  /**
   * ✨ Auto-filled from league template on save (e.g., "Central")
   */
  conference?: string | null;
  /**
   * Current standings information
   */
  standings?: {
    /**
     * Current rank/position
     */
    currentRank?: number | null;
    /**
     * Total teams in division
     */
    totalTeams?: number | null;
    /**
     * Wins
     */
    wins?: number | null;
    /**
     * Losses
     */
    losses?: number | null;
    /**
     * Ties
     */
    ties?: number | null;
    /**
     * Total points
     */
    points?: number | null;
    /**
     * Matches played
     */
    matchesPlayed?: number | null;
  };
  /**
   * Last sync from FaceIt API
   */
  lastSynced?: string | null;
  /**
   * Data source (for future integrations)
   */
  dataSource?: 'faceit' | null;
  /**
   * Hide this season from frontend historical display (data preserved)
   */
  hideHistoricalData?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏆 Define recurring match schedules for manually-scheduled tournaments. ⚠️ NOT needed for FaceIt tournaments - those use FaceIt Leagues instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-templates".
 */
export interface TournamentTemplate {
  id: number;
  /**
   * Tournament/League name (e.g., "Annihilation Tournament", "Summer Cup")
   */
  name: string;
  /**
   * When unchecked, stops auto-creating matches (use for breaks/off-season)
   */
  isActive?: boolean | null;
  /**
   * Teams participating in this tournament. Use the bulk selector below for easy multi-selection.
   */
  assignedTeams?: (number | Team)[] | null;
  /**
   * Define match schedule per division/region combination
   */
  scheduleRules?:
    | {
        region: 'NA' | 'EMEA' | 'SA' | 'all';
        division: 'Masters' | 'Expert' | 'Advanced' | 'Open' | 'all';
        /**
         * Number of matches to auto-create per week
         */
        matchesPerWeek: number;
        /**
         * When to schedule matches (can be rescheduled per match)
         */
        matchSlots?:
          | {
              dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
              /**
               * Time in HH:MM format (e.g., "20:00", "21:00")
               */
              time: string;
              timezone: 'CET' | 'EST';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🎙️ Manage production staff (casters, observers, producers) who work on match broadcasts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production".
 */
export interface Production {
  id: number;
  /**
   * Link to a person in the People collection. Social links are managed in the People collection.
   */
  person: number | Person;
  displayName?: string | null;
  /**
   * Auto-populated from the linked person's slug. This field is automatically set when you select a person.
   */
  slug?: string | null;
  /**
   * Production role. Select the combination that best describes their role(s).
   */
  type: 'caster' | 'observer' | 'producer' | 'observer-producer' | 'observer-producer-caster';
  updatedAt: string;
  createdAt: string;
}
/**
 * 👔 Manage organization staff members (owners, HR, moderators, managers, etc.). Staff can have multiple roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-staff".
 */
export interface OrganizationStaff {
  id: number;
  /**
   * Link to a person in the People collection. Social links are managed in the People collection.
   */
  person: number | Person;
  displayName?: string | null;
  /**
   * Auto-populated from the linked person's slug. This field is automatically set when you select a person.
   */
  slug?: string | null;
  /**
   * Select all roles this staff member holds. They can have multiple roles.
   */
  roles: (
    | 'owner'
    | 'co-owner'
    | 'hr'
    | 'moderator'
    | 'event-manager'
    | 'social-manager'
    | 'graphics'
    | 'media-editor'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚔️ Manage competitive matches for Elemental teams. Include match details, scores, streams, and VODs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * Match type affects how it appears in Weekly View
   */
  matchType: 'team-match' | 'organization-event' | 'show-match' | 'content-production';
  /**
   * Which ELMT team is playing (required for team matches)
   */
  team?: (number | null) | Team;
  /**
   * Opponent team name
   */
  opponent?: string | null;
  /**
   * Match date and time
   */
  date: string;
  region: 'NA' | 'EMEA' | 'SA';
  league: 'Masters' | 'Expert' | 'Advanced' | 'Open';
  /**
   * Season identifier (e.g., "S7 Regular Season")
   */
  season?: string | null;
  /**
   * Matches are automatically marked Complete 2 hours after their scheduled time
   */
  status: 'scheduled' | 'complete' | 'cancelled';
  /**
   * Match title (auto-generated from team + opponent if left blank). You can override the auto-generated title by entering a custom one here.
   */
  title?: string | null;
  titleCell?: string | null;
  score?: {
    /**
     * ELMT team score
     */
    elmtScore?: number | null;
    /**
     * Opponent team score
     */
    opponentScore?: number | null;
  };
  stream?: {
    /**
     * Twitch stream URL
     */
    url?: string | null;
    /**
     * Who is streaming (e.g., "twitch.tv/elmt_gg" or "twitch.tv/bullskunk")
     */
    streamedBy?: string | null;
  };
  /**
   * FACEIT lobby URL (auto-populated if synced from FaceIt)
   */
  faceitLobby?: string | null;
  /**
   * FaceIt Room ID (for generating room links) - auto-populated by sync
   */
  faceitRoomId?: string | null;
  /**
   * FaceIt Match ID - auto-populated by sync
   */
  faceitMatchId?: string | null;
  /**
   * VOD/replay URL (YouTube or Twitch)
   */
  vod?: string | null;
  productionWorkflow?: {
    priority?: ('none' | 'low' | 'medium' | 'high' | 'urgent') | null;
    /**
     * When this match was auto-generated
     */
    weekGenerated?: string | null;
    /**
     * Archived matches hidden from Weekly View
     */
    isArchived?: boolean | null;
    /**
     * Staff who are AVAILABLE to observe (not yet confirmed)
     */
    observerSignups?: (number | User)[] | null;
    /**
     * Staff who are AVAILABLE to produce (not yet confirmed)
     */
    producerSignups?: (number | User)[] | null;
    /**
     * Staff who are AVAILABLE to cast (not yet confirmed)
     */
    casterSignups?:
      | {
          user: number | User;
          style?: ('play-by-play' | 'color' | 'both') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * CONFIRMED observer who WILL work this match (1 max)
     */
    assignedObserver?: (number | null) | User;
    /**
     * CONFIRMED producer who WILL work this match (1 max)
     */
    assignedProducer?: (number | null) | User;
    /**
     * CONFIRMED casters who WILL work this match (2 max)
     */
    assignedCasters?:
      | {
          user: number | User;
          style?: ('play-by-play' | 'color' | 'both') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Auto-calculated: none/partial/full
     */
    coverageStatus?: ('none' | 'partial' | 'full') | null;
    /**
     * Include in Schedule Generator export
     */
    includeInSchedule?: boolean | null;
    /**
     * Internal production notes
     */
    productionNotes?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Auto-populated from FaceIt API
   */
  syncedFromFaceit?: boolean | null;
  /**
   * Link to FaceIt season data
   */
  faceitSeasonId?: (number | null) | FaceitSeason;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 👤 Manage admin users who can access the CMS. Assign roles to control what each user can edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Profile picture for your account
   */
  avatar?: (number | null) | Media;
  /**
   * Your Discord User ID (18-19 digits). Link your Discord account to track polls you create via /schedulepoll. Right-click your profile in Discord → Copy User ID (requires Developer Mode enabled in Discord settings).
   */
  discordId?: string | null;
  /**
   * User role determines what they can access and edit in the CMS.
   */
  role?: ('admin' | 'staff-manager' | 'team-manager' | 'user') | null;
  /**
   * For Team Managers: Restrict editing to only these teams. For Staff Managers & Admins: Quick access links to these teams (they can still edit all teams).
   */
  assignedTeams?: (number | Team)[] | null;
  /**
   * Grant access to department-specific tools and dashboards
   */
  departments?: {
    /**
     * Grants access to Production Dashboard (view schedule, sign up for matches)
     */
    isProductionStaff?: boolean | null;
    /**
     * Grants access to Social Media Dashboard (manage posts, content calendar)
     */
    isSocialMediaStaff?: boolean | null;
    /**
     * Grants access to Graphics Dashboard (view requests, manage projects)
     */
    isGraphicsStaff?: boolean | null;
    /**
     * Grants access to Video Editing Dashboard (clips, montages, seminars)
     */
    isVideoStaff?: boolean | null;
    /**
     * Grants access to Events Dashboard (movie nights, PUGs, seminars, tournaments)
     */
    isEventsStaff?: boolean | null;
    /**
     * Grants access to Scouting Dashboard (enemy team intel, research)
     */
    isScoutingStaff?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * 📱 Manage social media posts and content calendar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  /**
   * Internal title to identify this post (not shown publicly)
   */
  title: string;
  /**
   * The text content of the post (can be drafted later)
   */
  content?: string | null;
  /**
   * Category of the post (for tracking and color-coding)
   */
  postType:
    | 'Match Promo'
    | 'Stream Announcement'
    | 'Community Engagement'
    | 'Original Content'
    | 'Repost/Share'
    | 'Other';
  /**
   * Which platform this post is for
   */
  platform: 'Twitter/X';
  /**
   * When to post this content (optional for drafts/backlog)
   */
  scheduledDate?: string | null;
  /**
   * Current status of the post
   */
  status: 'Draft' | 'Ready for Review' | 'Approved' | 'Scheduled' | 'Posted';
  /**
   * SM staff member responsible for this post
   */
  assignedTo: number | User;
  /**
   * Admin who approved this post
   */
  approvedBy?: (number | null) | User;
  /**
   * If this post is promoting a specific match
   */
  relatedMatch?: (number | null) | Match;
  /**
   * Images, videos, or other media for this post
   */
  mediaAttachments?:
    | {
        media?: (number | null) | Media;
        /**
         * Or link to external media
         */
        url?: string | null;
        /**
         * Alt text for accessibility
         */
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes for reviewers (not visible in the post)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal - use Events Dashboard instead
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-anchor".
 */
export interface EventsAnchor {
  id: number;
  placeholder?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal - use Graphics Dashboard instead
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "graphics-anchor".
 */
export interface GraphicsAnchor {
  id: number;
  placeholder?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal - use Video Editing Dashboard instead
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-anchor".
 */
export interface VideoAnchor {
  id: number;
  placeholder?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📋 Manage open player positions and recruitment listings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-listings".
 */
export interface RecruitmentListing {
  id: number;
  /**
   * Type of position being recruited for
   */
  category: 'player' | 'team-staff' | 'org-staff';
  /**
   * Which team is recruiting (not applicable for organization-wide positions)
   */
  team?: (number | null) | Team;
  /**
   * What role is needed
   */
  role:
    | 'tank'
    | 'dps'
    | 'support'
    | 'coach'
    | 'manager'
    | 'assistant-coach'
    | 'moderator'
    | 'event-manager'
    | 'social-manager'
    | 'graphics'
    | 'media-editor'
    | 'caster'
    | 'observer'
    | 'producer'
    | 'observer-producer';
  /**
   * Describe what you're looking for (e.g., "We're looking for a Main Support. Must have a good attitude and can scrim 3 times a week")
   */
  requirements: string;
  /**
   * Status of this listing
   */
  status: 'open' | 'filled' | 'closed';
  /**
   * Person who filled this position (auto-set when filled)
   */
  filledBy?: (number | null) | Person;
  /**
   * User who created this listing
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📝 Review and manage recruitment applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-applications".
 */
export interface RecruitmentApplication {
  id: number;
  /**
   * Which listing this application is for
   */
  listing: number | RecruitmentListing;
  /**
   * Applicant's Discord username
   */
  discordHandle: string;
  /**
   * Applicant's introduction and why they want to join
   */
  aboutMe: string;
  /**
   * Current status of this application
   */
  status: 'new' | 'reviewing' | 'contacted' | 'tryout' | 'accepted' | 'rejected';
  /**
   * Internal notes visible only to managers and admins (not shown to applicant)
   */
  internalNotes?: string | null;
  /**
   * Archive old applications to hide them from active list
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📋 Universal task management for all departments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  /**
   * What needs to be done
   */
  title: string;
  /**
   * Detailed requirements and notes
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which department owns this task
   */
  department: 'graphics' | 'video' | 'events' | 'scouting' | 'production' | 'social-media';
  /**
   * Type of work (depends on department)
   */
  taskType?:
    | (
        | 'graphics-logo'
        | 'graphics-banner'
        | 'graphics-overlay'
        | 'graphics-thumbnail'
        | 'graphics-social-graphic'
        | 'graphics-other'
        | 'video-clips-of-week'
        | 'video-roster-reveal'
        | 'video-montage'
        | 'video-seminar-edit'
        | 'video-highlight-reel'
        | 'video-other'
        | 'events-movie-night'
        | 'events-game-night'
        | 'events-pug'
        | 'events-seminar'
        | 'events-tournament'
        | 'events-other'
        | 'scouting-team-research'
        | 'scouting-player-profile'
        | 'scouting-match-analysis'
        | 'scouting-other'
      )
    | null;
  /**
   * Current status
   */
  status: 'backlog' | 'in-progress' | 'review' | 'complete';
  /**
   * Priority level
   */
  priority: 'low' | 'medium' | 'high' | 'urgent';
  /**
   * When this is needed
   */
  dueDate?: string | null;
  /**
   * Staff member(s) working on this
   */
  assignedTo?: (number | User)[] | null;
  /**
   * Who submitted this request (for cross-department work)
   */
  requestedBy?: (number | null) | User;
  /**
   * Link to related content
   */
  relatedItems?: {
    /**
     * Related match (for graphics, clips, etc.)
     */
    match?: (number | null) | Match;
    /**
     * Related social media post
     */
    socialPost?: (number | null) | SocialPost;
    /**
     * Related recruitment listing (for scouting)
     */
    recruitmentListing?: (number | null) | RecruitmentListing;
    /**
     * Related team
     */
    team?: (number | null) | Team;
  };
  /**
   * Reference files, examples, deliverables
   */
  attachments?:
    | {
        file?: (number | null) | Media;
        /**
         * Description of this attachment
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Discussion thread
   */
  comments?:
    | {
        author: number | User;
        content: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Archive to hide from Kanban board (still searchable)
   */
  archived?: boolean | null;
  /**
   * When task was archived
   */
  archivedAt?: string | null;
  /**
   * When task was marked complete
   */
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📊 View poll history and results from Discord
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-polls".
 */
export interface DiscordPoll {
  id: number;
  /**
   * Name of the poll
   */
  pollName: string;
  /**
   * Discord message ID
   */
  messageId: string;
  /**
   * Discord channel ID where poll was posted
   */
  channelId: string;
  /**
   * Team this poll is for (optional)
   */
  team?: (number | null) | Team;
  dateRange?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Time slot for the schedule (e.g., "8-10 EST")
   */
  timeSlot?: string | null;
  /**
   * Current status of the poll
   */
  status?: ('active' | 'closed' | 'scheduled') | null;
  /**
   * Admin user who created this poll (linked via Discord ID)
   */
  createdBy?: (number | null) | User;
  /**
   * How the poll was created
   */
  createdVia?: ('discord-command' | 'admin-panel') | null;
  /**
   * Cached vote data from Discord (auto-updated)
   */
  votes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Generated schedule from poll results
   */
  schedule?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Saved Discord category templates for quick server setup
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-category-templates".
 */
export interface DiscordCategoryTemplate {
  id: number;
  /**
   * Template name (e.g., "Team Channels", "Staff Category")
   */
  name: string;
  /**
   * What this template is for
   */
  description?: string | null;
  /**
   * Original category name this was copied from
   */
  sourceCategory?: string | null;
  /**
   * Number of channels in this template
   */
  channelCount?: number | null;
  /**
   * Template configuration (channels, permissions, etc.)
   */
  templateData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🔍 System-generated log of user actions for security monitoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * User who performed the action
   */
  user?: (number | null) | User;
  /**
   * Type of action performed
   */
  action: 'login' | 'logout' | 'create' | 'delete' | 'update' | 'bulk';
  /**
   * Collection that was affected (e.g., teams, matches, users)
   */
  collection?: string | null;
  /**
   * ID of the document that was affected
   */
  documentId?: string | null;
  /**
   * Display name of the affected item
   */
  documentTitle?: string | null;
  /**
   * Additional context (role changes, bulk operation details, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP address of the request
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚠️ System-generated log of errors for debugging and monitoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs".
 */
export interface ErrorLog {
  id: number;
  /**
   * User who encountered the error
   */
  user?: (number | null) | User;
  /**
   * Category of error
   */
  errorType: 'api' | 'backend' | 'database' | 'frontend' | 'validation' | 'system';
  /**
   * Error message
   */
  message: string;
  /**
   * Stack trace for debugging
   */
  stack?: string | null;
  /**
   * URL where error occurred
   */
  url?: string | null;
  /**
   * Severity level of the error
   */
  severity: 'low' | 'medium' | 'high' | 'critical';
  /**
   * Mark this error as resolved/fixed
   */
  resolved?: boolean | null;
  /**
   * When the error was marked as resolved
   */
  resolvedAt?: string | null;
  /**
   * Admin notes about the error and resolution
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⏰ System-generated log of scheduled job executions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cron-job-runs".
 */
export interface CronJobRun {
  id: number;
  /**
   * Name of the cron job
   */
  jobName: 'smart-sync' | 'full-sync' | 'session-cleanup' | 'error-harvester';
  /**
   * Current status of the job
   */
  status: 'running' | 'success' | 'failed';
  /**
   * When the job started
   */
  startTime: string;
  /**
   * When the job completed
   */
  endTime?: string | null;
  /**
   * Duration in seconds
   */
  duration?: number | null;
  /**
   * Job-specific results (API calls, records synced, etc.)
   */
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error messages if job failed
   */
  errors?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 👥 Track active admin panel sessions for security monitoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-sessions".
 */
export interface ActiveSession {
  id: number;
  /**
   * User who owns this session
   */
  user: number | User;
  /**
   * When the user logged in
   */
  loginTime: string;
  /**
   * Last activity timestamp
   */
  lastActivity: string;
  /**
   * IP address of the session
   */
  ipAddress?: string | null;
  /**
   * Browser/client information
   */
  userAgent?: string | null;
  /**
   * Whether this session is currently active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pairs of people with similar names that are actually different people
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ignored-duplicates".
 */
export interface IgnoredDuplicate {
  id: number;
  /**
   * First person in the pair
   */
  person1: number | Person;
  /**
   * Second person in the pair
   */
  person2: number | Person;
  /**
   * Display label (auto-generated)
   */
  label: string;
  /**
   * Optional note explaining why these are different people
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🔗 Generate invite links for new users with pre-configured permissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-links".
 */
export interface InviteLink {
  id: number;
  /**
   * Unique token for this invite link (auto-generated)
   */
  token: string;
  /**
   * The role the new user will be assigned when they sign up
   */
  role: 'admin' | 'staff-manager' | 'team-manager' | 'user';
  /**
   * Teams the new user will have access to (only applicable for Team Managers and Staff Managers)
   */
  assignedTeams?: (number | Team)[] | null;
  /**
   * Which departments this user will have access to (mainly for User role)
   */
  departments?: {
    /**
     * Grant access to Production Dashboard for signing up to matches (casters, observers, producers)
     */
    isProductionStaff?: boolean | null;
    /**
     * Grants access to the Social Media Dashboard (manage posts, content calendar)
     */
    isSocialMediaStaff?: boolean | null;
    /**
     * Grants access to the Graphics Dashboard (create graphics, manage requests)
     */
    isGraphicsStaff?: boolean | null;
    /**
     * Grants access to the Video Editing Dashboard (clips, montages, edits)
     */
    isVideoStaff?: boolean | null;
    /**
     * Grants access to the Events Dashboard (movie nights, PUGs, seminars)
     */
    isEventsStaff?: boolean | null;
    /**
     * Grants access to the Scouting Dashboard (team research, player profiles)
     */
    isScoutingStaff?: boolean | null;
  };
  /**
   * Optional: Pre-assign an email address for this invite
   */
  email?: string | null;
  /**
   * When this invite link expires (default: 7 days from creation)
   */
  expiresAt: string;
  /**
   * When this invite was used (null if not yet used)
   */
  usedAt?: string | null;
  /**
   * The user who used this invite
   */
  usedBy?: (number | null) | User;
  /**
   * The admin who created this invite
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'faceit-leagues';
        value: number | FaceitLeague;
      } | null)
    | ({
        relationTo: 'production';
        value: number | Production;
      } | null)
    | ({
        relationTo: 'organization-staff';
        value: number | OrganizationStaff;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'tournament-templates';
        value: number | TournamentTemplate;
      } | null)
    | ({
        relationTo: 'faceit-seasons';
        value: number | FaceitSeason;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'events-anchor';
        value: number | EventsAnchor;
      } | null)
    | ({
        relationTo: 'graphics-anchor';
        value: number | GraphicsAnchor;
      } | null)
    | ({
        relationTo: 'video-anchor';
        value: number | VideoAnchor;
      } | null)
    | ({
        relationTo: 'recruitment-listings';
        value: number | RecruitmentListing;
      } | null)
    | ({
        relationTo: 'recruitment-applications';
        value: number | RecruitmentApplication;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'discord-polls';
        value: number | DiscordPoll;
      } | null)
    | ({
        relationTo: 'discord-category-templates';
        value: number | DiscordCategoryTemplate;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'error-logs';
        value: number | ErrorLog;
      } | null)
    | ({
        relationTo: 'cron-job-runs';
        value: number | CronJobRun;
      } | null)
    | ({
        relationTo: 'active-sessions';
        value: number | ActiveSession;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'ignored-duplicates';
        value: number | IgnoredDuplicate;
      } | null)
    | ({
        relationTo: 'invite-links';
        value: number | InviteLink;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  photo?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        twitch?: T;
        youtube?: T;
        instagram?: T;
        tiktok?: T;
        customLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  region?: T;
  rating?: T;
  themeColor?: T;
  bio?: T;
  active?: T;
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  manager?:
    | T
    | {
        person?: T;
        id?: T;
      };
  coaches?:
    | T
    | {
        person?: T;
        id?: T;
      };
  captain?:
    | T
    | {
        person?: T;
        id?: T;
      };
  coCaptain?: T;
  roster?:
    | T
    | {
        person?: T;
        role?: T;
        id?: T;
      };
  subs?:
    | T
    | {
        person?: T;
        id?: T;
      };
  faceitEnabled?: T;
  faceitTeamId?: T;
  currentFaceitLeague?: T;
  faceitShowCompetitiveSection?: T;
  currentFaceitSeason?: T;
  slug?: T;
  activeTournaments?: T;
  competitiveRating?: T;
  discordCardMessageId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faceit-leagues_select".
 */
export interface FaceitLeaguesSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  seasonNumber?: T;
  division?: T;
  region?: T;
  conference?: T;
  leagueId?: T;
  seasonId?: T;
  stageId?: T;
  championshipId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production_select".
 */
export interface ProductionSelect<T extends boolean = true> {
  person?: T;
  displayName?: T;
  slug?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-staff_select".
 */
export interface OrganizationStaffSelect<T extends boolean = true> {
  person?: T;
  displayName?: T;
  slug?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  matchType?: T;
  team?: T;
  opponent?: T;
  date?: T;
  region?: T;
  league?: T;
  season?: T;
  status?: T;
  title?: T;
  titleCell?: T;
  score?:
    | T
    | {
        elmtScore?: T;
        opponentScore?: T;
      };
  stream?:
    | T
    | {
        url?: T;
        streamedBy?: T;
      };
  faceitLobby?: T;
  faceitRoomId?: T;
  faceitMatchId?: T;
  vod?: T;
  productionWorkflow?:
    | T
    | {
        priority?: T;
        weekGenerated?: T;
        isArchived?: T;
        observerSignups?: T;
        producerSignups?: T;
        casterSignups?:
          | T
          | {
              user?: T;
              style?: T;
              id?: T;
            };
        assignedObserver?: T;
        assignedProducer?: T;
        assignedCasters?:
          | T
          | {
              user?: T;
              style?: T;
              id?: T;
            };
        coverageStatus?: T;
        includeInSchedule?: T;
        productionNotes?: T;
      };
  syncedFromFaceit?: T;
  faceitSeasonId?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-templates_select".
 */
export interface TournamentTemplatesSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  assignedTeams?: T;
  scheduleRules?:
    | T
    | {
        region?: T;
        division?: T;
        matchesPerWeek?: T;
        matchSlots?:
          | T
          | {
              dayOfWeek?: T;
              time?: T;
              timezone?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faceit-seasons_select".
 */
export interface FaceitSeasonsSelect<T extends boolean = true> {
  team?: T;
  faceitLeague?: T;
  faceitTeamId?: T;
  championshipId?: T;
  leagueId?: T;
  seasonId?: T;
  stageId?: T;
  seasonName?: T;
  isActive?: T;
  division?: T;
  region?: T;
  conference?: T;
  standings?:
    | T
    | {
        currentRank?: T;
        totalTeams?: T;
        wins?: T;
        losses?: T;
        ties?: T;
        points?: T;
        matchesPlayed?: T;
      };
  lastSynced?: T;
  dataSource?: T;
  hideHistoricalData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  postType?: T;
  platform?: T;
  scheduledDate?: T;
  status?: T;
  assignedTo?: T;
  approvedBy?: T;
  relatedMatch?: T;
  mediaAttachments?:
    | T
    | {
        media?: T;
        url?: T;
        altText?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-anchor_select".
 */
export interface EventsAnchorSelect<T extends boolean = true> {
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "graphics-anchor_select".
 */
export interface GraphicsAnchorSelect<T extends boolean = true> {
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-anchor_select".
 */
export interface VideoAnchorSelect<T extends boolean = true> {
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-listings_select".
 */
export interface RecruitmentListingsSelect<T extends boolean = true> {
  category?: T;
  team?: T;
  role?: T;
  requirements?: T;
  status?: T;
  filledBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-applications_select".
 */
export interface RecruitmentApplicationsSelect<T extends boolean = true> {
  listing?: T;
  discordHandle?: T;
  aboutMe?: T;
  status?: T;
  internalNotes?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  department?: T;
  taskType?: T;
  status?: T;
  priority?: T;
  dueDate?: T;
  assignedTo?: T;
  requestedBy?: T;
  relatedItems?:
    | T
    | {
        match?: T;
        socialPost?: T;
        recruitmentListing?: T;
        team?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  comments?:
    | T
    | {
        author?: T;
        content?: T;
        createdAt?: T;
        id?: T;
      };
  archived?: T;
  archivedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-polls_select".
 */
export interface DiscordPollsSelect<T extends boolean = true> {
  pollName?: T;
  messageId?: T;
  channelId?: T;
  team?: T;
  dateRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  timeSlot?: T;
  status?: T;
  createdBy?: T;
  createdVia?: T;
  votes?: T;
  schedule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-category-templates_select".
 */
export interface DiscordCategoryTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  sourceCategory?: T;
  channelCount?: T;
  templateData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  documentTitle?: T;
  metadata?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs_select".
 */
export interface ErrorLogsSelect<T extends boolean = true> {
  user?: T;
  errorType?: T;
  message?: T;
  stack?: T;
  url?: T;
  severity?: T;
  resolved?: T;
  resolvedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cron-job-runs_select".
 */
export interface CronJobRunsSelect<T extends boolean = true> {
  jobName?: T;
  status?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  summary?: T;
  errors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-sessions_select".
 */
export interface ActiveSessionsSelect<T extends boolean = true> {
  user?: T;
  loginTime?: T;
  lastActivity?: T;
  ipAddress?: T;
  userAgent?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  discordId?: T;
  role?: T;
  assignedTeams?: T;
  departments?:
    | T
    | {
        isProductionStaff?: T;
        isSocialMediaStaff?: T;
        isGraphicsStaff?: T;
        isVideoStaff?: T;
        isEventsStaff?: T;
        isScoutingStaff?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ignored-duplicates_select".
 */
export interface IgnoredDuplicatesSelect<T extends boolean = true> {
  person1?: T;
  person2?: T;
  label?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-links_select".
 */
export interface InviteLinksSelect<T extends boolean = true> {
  token?: T;
  role?: T;
  assignedTeams?: T;
  departments?:
    | T
    | {
        isProductionStaff?: T;
        isSocialMediaStaff?: T;
        isGraphicsStaff?: T;
        isVideoStaff?: T;
        isEventsStaff?: T;
        isScoutingStaff?: T;
      };
  email?: T;
  expiresAt?: T;
  usedAt?: T;
  usedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📺 Manage weekly match coverage, staff assignments, and broadcast schedule
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-dashboard".
 */
export interface ProductionDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📱 Manage social media posts, content calendar, and posting schedule
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-settings".
 */
export interface SocialMediaSetting {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ⚙️ Configure templates, goals, and content guidelines for social media posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-config".
 */
export interface SocialMediaConfig {
  id: number;
  /**
   * Create reusable templates for your social media team
   */
  postTemplates?:
    | {
        /**
         * Template name (e.g., "Match Day Announcement")
         */
        name: string;
        /**
         * Associated post type
         */
        postType:
          | 'Match Promo'
          | 'Stream Announcement'
          | 'Community Engagement'
          | 'Original Content'
          | 'Repost/Share'
          | 'Other';
        /**
         * Template text with placeholders. Use {{placeholderName}} for any dynamic value (e.g., {{team_1}}, {{team_2}}, {{matchTime}}, {{url}})
         */
        templateText: string;
        /**
         * Recommended graphics or media type (e.g., "Team banner", "Stream overlay")
         */
        suggestedMedia?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set weekly posting targets to encourage consistent output
   */
  weeklyGoals?: {
    /**
     * Target number of posts per week
     */
    totalPostsPerWeek?: number | null;
    /**
     * Target match promotion posts
     */
    matchPromos?: number | null;
    /**
     * Target stream announcement posts
     */
    streamAnnouncements?: number | null;
    /**
     * Target community engagement posts
     */
    communityEngagement?: number | null;
    /**
     * Target original content posts
     */
    originalContent?: number | null;
  };
  /**
   * Best practices, brand voice, and posting guidelines for the team
   */
  contentGuidelines?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🎨 Manage graphics requests, projects, and asset library
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "graphics-dashboard".
 */
export interface GraphicsDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🎬 Manage video projects, clips of the week, and edits
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-editing-dashboard".
 */
export interface VideoEditingDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🎉 Manage movie nights, game nights, PUGs, seminars, and tournaments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-dashboard".
 */
export interface EventsDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🔍 Manage enemy team research, player profiles, and match analysis
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scouting-dashboard".
 */
export interface ScoutingDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Discord server structure, channels, categories, roles, and members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-server-manager".
 */
export interface DiscordServerManager {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🔍 View user action logs for security monitoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log-viewer".
 */
export interface AuditLogViewer {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ⏰ Monitor scheduled job executions and performance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cron-monitor".
 */
export interface CronMonitor {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ⚠️ Monitor and track application errors for debugging.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-dashboard".
 */
export interface ErrorDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 👥 Monitor currently logged-in admin panel users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-sessions-viewer".
 */
export interface ActiveSessionsViewer {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📊 System overview and health monitoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-health".
 */
export interface DatabaseHealth {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📊 Check and fix data consistency issues across collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-consistency".
 */
export interface DataConsistency {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-harvester-state".
 */
export interface ErrorHarvesterState {
  id: number;
  /**
   * Timestamp of when the error harvester last ran
   */
  lastCheckedAt?: string | null;
  /**
   * Number of errors found in the last run
   */
  lastRunErrors?: number | null;
  /**
   * Total number of times the harvester has run
   */
  totalRunCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-dashboard_select".
 */
export interface ProductionDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-settings_select".
 */
export interface SocialMediaSettingsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-config_select".
 */
export interface SocialMediaConfigSelect<T extends boolean = true> {
  postTemplates?:
    | T
    | {
        name?: T;
        postType?: T;
        templateText?: T;
        suggestedMedia?: T;
        id?: T;
      };
  weeklyGoals?:
    | T
    | {
        totalPostsPerWeek?: T;
        matchPromos?: T;
        streamAnnouncements?: T;
        communityEngagement?: T;
        originalContent?: T;
      };
  contentGuidelines?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "graphics-dashboard_select".
 */
export interface GraphicsDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-editing-dashboard_select".
 */
export interface VideoEditingDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-dashboard_select".
 */
export interface EventsDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scouting-dashboard_select".
 */
export interface ScoutingDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-server-manager_select".
 */
export interface DiscordServerManagerSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log-viewer_select".
 */
export interface AuditLogViewerSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cron-monitor_select".
 */
export interface CronMonitorSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-dashboard_select".
 */
export interface ErrorDashboardSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-sessions-viewer_select".
 */
export interface ActiveSessionsViewerSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-health_select".
 */
export interface DatabaseHealthSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-consistency_select".
 */
export interface DataConsistencySelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-harvester-state_select".
 */
export interface ErrorHarvesterStateSelect<T extends boolean = true> {
  lastCheckedAt?: T;
  lastRunErrors?: T;
  totalRunCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}