/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    people: Person;
    teams: Team;
    matches: Match;
    production: Production;
    'organization-staff': OrganizationStaff;
    users: User;
    'ignored-duplicates': IgnoredDuplicate;
    'recruitment-listings': RecruitmentListing;
    'recruitment-applications': RecruitmentApplication;
    'invite-links': InviteLink;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    production: ProductionSelect<false> | ProductionSelect<true>;
    'organization-staff': OrganizationStaffSelect<false> | OrganizationStaffSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'ignored-duplicates': IgnoredDuplicatesSelect<false> | IgnoredDuplicatesSelect<true>;
    'recruitment-listings': RecruitmentListingsSelect<false> | RecruitmentListingsSelect<true>;
    'recruitment-applications': RecruitmentApplicationsSelect<false> | RecruitmentApplicationsSelect<true>;
    'invite-links': InviteLinksSelect<false> | InviteLinksSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'data-consistency': DataConsistency;
    'schedule-generator': ScheduleGenerator;
    'user-profile': UserProfile;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'data-consistency': DataConsistencySelect<false> | DataConsistencySelect<true>;
    'schedule-generator': ScheduleGeneratorSelect<false> | ScheduleGeneratorSelect<true>;
    'user-profile': UserProfileSelect<false> | UserProfileSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 📄 Create and edit website pages with rich content, blocks, and SEO settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🖼️ Upload and manage images, videos, and other media files used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * 👥 Centralized collection for all people (players, staff, casters, etc.). This is the single source of truth for person profiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * Full display name. This name will be used across all teams and staff positions. Tip: Use the exact name format you want displayed (e.g., "Malevolence" not "malevolence").
   */
  name: string;
  /**
   * Auto-generated from name. You can customize it if needed.
   */
  slug?: string | null;
  /**
   * Optional biography or description
   */
  bio?: string | null;
  /**
   * Profile photo (optional)
   */
  photo?: (number | null) | Media;
  /**
   * Social media links. These will be displayed on player pages. Tip: Use full URLs (e.g., https://twitter.com/username) for best results.
   */
  socialLinks?: {
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * Twitch channel URL
     */
    twitch?: string | null;
    /**
     * YouTube channel URL
     */
    youtube?: string | null;
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * TikTok profile URL
     */
    tiktok?: string | null;
    /**
     * Add any additional social media or personal links with custom labels
     */
    customLinks?:
      | {
          /**
           * Display name for this link (e.g., "Discord", "Website", "Linktree")
           */
          label: string;
          /**
           * Full URL for this link
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Internal notes about this person (not displayed publicly)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏆 Manage all Elemental teams, including rosters, staff, and achievements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * Team display name (e.g., "Garden", "Dragon", "Fire")
   */
  name: string;
  /**
   * Path to logo image (e.g., /logos/elmt_garden.png). Logo should be uploaded to /public/logos/
   */
  logo: string;
  /**
   * Geographic region where the team competes
   */
  region?: ('NA' | 'EMEA' | 'SA' | 'Other') | null;
  /**
   * Team skill rating or tier (e.g., "4.5K", "FACEIT Masters", "FACEIT Expert", "FACEIT Advanced", "3.5K")
   */
  rating?: string | null;
  /**
   * Custom theme color for the team page hero background. Pick a color that complements the logo. Leave empty to auto-detect based on team name.
   */
  themeColor?: string | null;
  /**
   * Optional team bio or description to display on the team page. Great for team history, philosophy, or fun facts!
   */
  bio?: string | null;
  /**
   * Whether this team is currently active and competing
   */
  active?: boolean | null;
  /**
   * Notable achievements and accomplishments for this team
   */
  achievements?:
    | {
        /**
         * Achievement text (e.g., "Faceit S5 Advanced Champions")
         */
        achievement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Team managers. Use the Person field to link to the People collection (recommended). Tip: A person can be both manager and coach - they will appear once with both roles on their player page. Click "Create Person" to add someone new without leaving this page.
   */
  manager?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Team coaches. Use the Person field to link to the People collection (recommended). Tip: A person can be both manager and coach - they will appear once with both roles on their player page. Click "Create Person" to add someone new without leaving this page.
   */
  coaches?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Team captains. Use the Person field to link to the People collection (recommended). Tip: A player can be both captain and on the roster - they will appear once with both roles. Click "Create Person" to add someone new without leaving this page.
   */
  captain?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * Co-captain (link to People collection).
   */
  coCaptain?: (number | null) | Person;
  /**
   * Active roster players. Use the Person field to link to the People collection (recommended). Each player must have a role (Tank, DPS, or Support). Tip: Click "Create Person" to add someone new without leaving this page.
   */
  roster?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        /**
         * Player role in-game
         */
        role: 'tank' | 'dps' | 'support';
        id?: string | null;
      }[]
    | null;
  /**
   * Substitute players who can fill in when needed. Use the Person field to link to the People collection (recommended), or use Name field for backward compatibility.
   */
  subs?:
    | {
        /**
         * Link to a person in the People collection. Social links are managed in the People collection.
         */
        person: number | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚔️ Manage competitive matches for Elemental teams. Include match details, scores, streams, and VODs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * Which ELMT team is playing. Tip: Only select teams from your organization. This will create a link to the team page on the match schedule.
   */
  team: number | Team;
  /**
   * Opponent team name
   */
  opponent: string;
  /**
   * Match date and time
   */
  date: string;
  region: 'NA' | 'EMEA' | 'SA';
  league: 'Masters' | 'Expert' | 'Advanced' | 'Open';
  /**
   * Season identifier (e.g., "S7 Regular Season")
   */
  season?: string | null;
  /**
   * Upcoming/Live/Completed status is automatically determined based on match date and time
   */
  status: 'scheduled' | 'cancelled';
  /**
   * Match title (auto-generated from team + opponent if left blank). You can override the auto-generated title by entering a custom one here.
   */
  title?: string | null;
  titleCell?: string | null;
  score?: {
    /**
     * ELMT team score
     */
    elmtScore?: number | null;
    /**
     * Opponent team score
     */
    opponentScore?: number | null;
  };
  stream?: {
    /**
     * Twitch stream URL
     */
    url?: string | null;
    /**
     * Who is streaming (e.g., "twitch.tv/elmt_gg" or "twitch.tv/bullskunk")
     */
    streamedBy?: string | null;
  };
  /**
   * FACEIT lobby URL
   */
  faceitLobby?: string | null;
  /**
   * VOD/replay URL (YouTube or Twitch)
   */
  vod?: string | null;
  /**
   * Producers and/or Observers for this match. Add one entry if one person is doing both roles, or add multiple entries for separate producer and observer.
   */
  producersObservers?:
    | {
        /**
         * Select existing producer/observer from Production Staff (or leave empty and enter name manually below)
         */
        staff?: (number | null) | Production;
        /**
         * Producer/Observer name (only fill if not selecting from Production Staff above)
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Casters for this match
   */
  casters?:
    | {
        /**
         * Select existing caster (or leave empty and enter name manually below)
         */
        caster?: (number | null) | Production;
        /**
         * Caster name (only fill if not selecting from Production Staff above)
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🎙️ Manage production staff (casters, observers, producers) who work on match broadcasts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production".
 */
export interface Production {
  id: number;
  /**
   * Link to a person in the People collection. Social links are managed in the People collection.
   */
  person: number | Person;
  displayName?: string | null;
  /**
   * Auto-populated from the linked person's slug. This field is automatically set when you select a person.
   */
  slug?: string | null;
  /**
   * Production role. Select the combination that best describes their role(s).
   */
  type: 'caster' | 'observer' | 'producer' | 'observer-producer' | 'observer-producer-caster';
  updatedAt: string;
  createdAt: string;
}
/**
 * 👔 Manage organization staff members (owners, HR, moderators, managers, etc.). Staff can have multiple roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-staff".
 */
export interface OrganizationStaff {
  id: number;
  /**
   * Link to a person in the People collection. Social links are managed in the People collection.
   */
  person: number | Person;
  displayName?: string | null;
  /**
   * Auto-populated from the linked person's slug. This field is automatically set when you select a person.
   */
  slug?: string | null;
  /**
   * Select all roles this staff member holds. They can have multiple roles.
   */
  roles: (
    | 'owner'
    | 'co-owner'
    | 'hr'
    | 'moderator'
    | 'event-manager'
    | 'social-manager'
    | 'graphics'
    | 'media-editor'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * 👤 Manage admin users who can access the CMS. Assign roles to control what each user can edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Profile picture for your account
   */
  avatar?: (number | null) | Media;
  /**
   * User role determines what they can access and edit in the CMS.
   */
  role: 'admin' | 'team-manager' | 'staff-manager';
  /**
   * For Team Managers: Restrict editing to only these teams. For Staff Managers & Admins: Quick access links to these teams (they can still edit all teams).
   */
  assignedTeams?: (number | Team)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Pairs of people with similar names that are actually different people
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ignored-duplicates".
 */
export interface IgnoredDuplicate {
  id: number;
  /**
   * First person in the pair
   */
  person1: number | Person;
  /**
   * Second person in the pair
   */
  person2: number | Person;
  /**
   * Display label (auto-generated)
   */
  label: string;
  /**
   * Optional note explaining why these are different people
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📋 Manage open player positions and recruitment listings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-listings".
 */
export interface RecruitmentListing {
  id: number;
  /**
   * Type of position being recruited for
   */
  category: 'player' | 'team-staff' | 'org-staff';
  /**
   * Which team is recruiting (not applicable for organization-wide positions)
   */
  team?: (number | null) | Team;
  /**
   * What role is needed
   */
  role:
    | 'tank'
    | 'dps'
    | 'support'
    | 'coach'
    | 'manager'
    | 'assistant-coach'
    | 'moderator'
    | 'event-manager'
    | 'social-manager'
    | 'graphics'
    | 'media-editor'
    | 'caster'
    | 'observer'
    | 'producer'
    | 'observer-producer';
  /**
   * Describe what you're looking for (e.g., "We're looking for a Main Support. Must have a good attitude and can scrim 3 times a week")
   */
  requirements: string;
  /**
   * Status of this listing
   */
  status: 'open' | 'filled' | 'closed';
  /**
   * Person who filled this position (auto-set when filled)
   */
  filledBy?: (number | null) | Person;
  /**
   * User who created this listing
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📝 Review and manage recruitment applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-applications".
 */
export interface RecruitmentApplication {
  id: number;
  /**
   * Which listing this application is for
   */
  listing: number | RecruitmentListing;
  /**
   * Applicant's Discord username
   */
  discordHandle: string;
  /**
   * Applicant's introduction and why they want to join
   */
  aboutMe: string;
  /**
   * Current status of this application
   */
  status: 'new' | 'reviewing' | 'contacted' | 'tryout' | 'accepted' | 'rejected';
  /**
   * Internal notes visible only to managers and admins (not shown to applicant)
   */
  internalNotes?: string | null;
  /**
   * Archive old applications to hide them from active list
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🔗 Generate invite links for new users with pre-configured permissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-links".
 */
export interface InviteLink {
  id: number;
  /**
   * Unique token for this invite link (auto-generated)
   */
  token: string;
  /**
   * The role the new user will be assigned when they sign up
   */
  role: 'admin' | 'team-manager' | 'staff-manager';
  /**
   * Teams the new user will have access to (for Team Managers and Staff Managers)
   */
  assignedTeams?: (number | Team)[] | null;
  /**
   * Optional: Pre-assign an email address for this invite
   */
  email?: string | null;
  /**
   * When this invite link expires (default: 7 days from creation)
   */
  expiresAt: string;
  /**
   * When this invite was used (null if not yet used)
   */
  usedAt?: string | null;
  /**
   * The user who used this invite
   */
  usedBy?: (number | null) | User;
  /**
   * The admin who created this invite
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'production';
        value: number | Production;
      } | null)
    | ({
        relationTo: 'organization-staff';
        value: number | OrganizationStaff;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'ignored-duplicates';
        value: number | IgnoredDuplicate;
      } | null)
    | ({
        relationTo: 'recruitment-listings';
        value: number | RecruitmentListing;
      } | null)
    | ({
        relationTo: 'recruitment-applications';
        value: number | RecruitmentApplication;
      } | null)
    | ({
        relationTo: 'invite-links';
        value: number | InviteLink;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  photo?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        twitch?: T;
        youtube?: T;
        instagram?: T;
        tiktok?: T;
        customLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  region?: T;
  rating?: T;
  themeColor?: T;
  bio?: T;
  active?: T;
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  manager?:
    | T
    | {
        person?: T;
        id?: T;
      };
  coaches?:
    | T
    | {
        person?: T;
        id?: T;
      };
  captain?:
    | T
    | {
        person?: T;
        id?: T;
      };
  coCaptain?: T;
  roster?:
    | T
    | {
        person?: T;
        role?: T;
        id?: T;
      };
  subs?:
    | T
    | {
        person?: T;
        id?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  team?: T;
  opponent?: T;
  date?: T;
  region?: T;
  league?: T;
  season?: T;
  status?: T;
  title?: T;
  titleCell?: T;
  score?:
    | T
    | {
        elmtScore?: T;
        opponentScore?: T;
      };
  stream?:
    | T
    | {
        url?: T;
        streamedBy?: T;
      };
  faceitLobby?: T;
  vod?: T;
  producersObservers?:
    | T
    | {
        staff?: T;
        name?: T;
        id?: T;
      };
  casters?:
    | T
    | {
        caster?: T;
        name?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production_select".
 */
export interface ProductionSelect<T extends boolean = true> {
  person?: T;
  displayName?: T;
  slug?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-staff_select".
 */
export interface OrganizationStaffSelect<T extends boolean = true> {
  person?: T;
  displayName?: T;
  slug?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  assignedTeams?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ignored-duplicates_select".
 */
export interface IgnoredDuplicatesSelect<T extends boolean = true> {
  person1?: T;
  person2?: T;
  label?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-listings_select".
 */
export interface RecruitmentListingsSelect<T extends boolean = true> {
  category?: T;
  team?: T;
  role?: T;
  requirements?: T;
  status?: T;
  filledBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-applications_select".
 */
export interface RecruitmentApplicationsSelect<T extends boolean = true> {
  listing?: T;
  discordHandle?: T;
  aboutMe?: T;
  status?: T;
  internalNotes?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-links_select".
 */
export interface InviteLinksSelect<T extends boolean = true> {
  token?: T;
  role?: T;
  assignedTeams?: T;
  email?: T;
  expiresAt?: T;
  usedAt?: T;
  usedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📊 Check and fix data consistency issues across collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-consistency".
 */
export interface DataConsistency {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📋 Generate Discord announcements from upcoming matches.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-generator".
 */
export interface ScheduleGenerator {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 👤 View and manage your account settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profile".
 */
export interface UserProfile {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-consistency_select".
 */
export interface DataConsistencySelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-generator_select".
 */
export interface ScheduleGeneratorSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profile_select".
 */
export interface UserProfileSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}